<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ZFBrowser</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>H:\SteamLibrary\steamapps\common\重生2我独自逆袭Demo\重生2我独自逆袭_BackUpThisFolder_ButDontShipItWithYourGame\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>H:\SteamLibrary\steamapps\common\重生2我独自逆袭Demo\重生2我独自逆袭_BackUpThisFolder_ButDontShipItWithYourGame\Managed\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>H:\SteamLibrary\steamapps\common\重生2我独自逆袭Demo\重生2我独自逆袭_BackUpThisFolder_ButDontShipItWithYourGame\Managed\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>H:\SteamLibrary\steamapps\common\重生2我独自逆袭Demo\重生2我独自逆袭_BackUpThisFolder_ButDontShipItWithYourGame\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>H:\SteamLibrary\steamapps\common\重生2我独自逆袭Demo\重生2我独自逆袭_BackUpThisFolder_ButDontShipItWithYourGame\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.XRModule">
      <HintPath>H:\SteamLibrary\steamapps\common\重生2我独自逆袭Demo\重生2我独自逆袭_BackUpThisFolder_ButDontShipItWithYourGame\Managed\UnityEngine.XRModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>H:\SteamLibrary\steamapps\common\重生2我独自逆袭Demo\重生2我独自逆袭_BackUpThisFolder_ButDontShipItWithYourGame\Managed\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VRModule">
      <HintPath>H:\SteamLibrary\steamapps\common\重生2我独自逆袭Demo\重生2我独自逆袭_BackUpThisFolder_ButDontShipItWithYourGame\Managed\UnityEngine.VRModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>H:\SteamLibrary\steamapps\common\重生2我独自逆袭Demo\重生2我独自逆袭_BackUpThisFolder_ButDontShipItWithYourGame\Managed\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>H:\SteamLibrary\steamapps\common\重生2我独自逆袭Demo\重生2我独自逆袭_BackUpThisFolder_ButDontShipItWithYourGame\Managed\System.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>