using DG.Tweening.Core.Enums;
using UnityEngine;

namespace DG.Tweening.Core;

public static class Debugger
{
	internal static class Sequence
	{
		public static void LogAddToNullSequence()
		{
			LogWarning("You can't add elements to a NULL Sequence");
		}

		public static void LogAddToInactiveSequence()
		{
			LogWarning("You can't add elements to an inactive/killed Sequence");
		}

		public static void LogAddToLockedSequence()
		{
			LogWarning("The Sequence has started and is now locked, you can only elements to a Sequence before it starts");
		}

		public static void LogAddNullTween()
		{
			LogWarning("You can't add a NULL tween to a Sequence");
		}

		public static void LogAddInactiveTween(Tween t)
		{
			LogWarning("You can't add an inactive/killed tween to a Sequence", t);
		}

		public static void LogAddAlreadySequencedTween(Tween t)
		{
			LogWarning("You can't add a tween that is already nested into a Sequence to another Sequence", t);
		}
	}

	private static int _logPriority;

	private const string _LogPrefix = "<color=#0099bc><b>DOTWEEN ► </b></color>";

	public static int logPriority => _logPriority;

	public static void Log(object message)
	{
		string text = "<color=#0099bc><b>DOTWEEN ► </b></color>" + message;
		if (DOTween.onWillLog == null || DOTween.onWillLog(LogType.Log, text))
		{
			Debug.Log(text);
		}
	}

	public static void LogWarning(object message, Tween t = null)
	{
		string text = ((!DOTween.debugMode) ? ("<color=#0099bc><b>DOTWEEN ► </b></color>" + message) : ("<color=#0099bc><b>DOTWEEN ► </b></color>" + GetDebugDataMessage(t) + message));
		if (DOTween.onWillLog == null || DOTween.onWillLog(LogType.Warning, text))
		{
			Debug.LogWarning(text);
		}
	}

	public static void LogError(object message, Tween t = null)
	{
		string text = ((!DOTween.debugMode) ? ("<color=#0099bc><b>DOTWEEN ► </b></color>" + message) : ("<color=#0099bc><b>DOTWEEN ► </b></color>" + GetDebugDataMessage(t) + message));
		if (DOTween.onWillLog == null || DOTween.onWillLog(LogType.Error, text))
		{
			Debug.LogError(text);
		}
	}

	public static void LogSafeModeCapturedError(object message, Tween t = null)
	{
		string text = ((!DOTween.debugMode) ? ("<color=#0099bc><b>DOTWEEN ► </b></color>" + message) : ("<color=#0099bc><b>DOTWEEN ► </b></color>" + GetDebugDataMessage(t) + message));
		if (DOTween.onWillLog == null || DOTween.onWillLog(LogType.Log, text))
		{
			switch (DOTween.safeModeLogBehaviour)
			{
			case SafeModeLogBehaviour.Normal:
				Debug.Log(text);
				break;
			case SafeModeLogBehaviour.Warning:
				Debug.LogWarning(text);
				break;
			case SafeModeLogBehaviour.Error:
				Debug.LogError(text);
				break;
			}
		}
	}

	public static void LogReport(object message)
	{
		string text = string.Format("<color=#00B500FF>{0} REPORT ►</color> {1}", "<color=#0099bc><b>DOTWEEN ► </b></color>", message);
		if (DOTween.onWillLog == null || DOTween.onWillLog(LogType.Log, text))
		{
			Debug.Log(text);
		}
	}

	public static void LogSafeModeReport(object message)
	{
		string text = string.Format("<color=#ff7337>{0} SAFE MODE ►</color> {1}", "<color=#0099bc><b>DOTWEEN ► </b></color>", message);
		if (DOTween.onWillLog == null || DOTween.onWillLog(LogType.Log, text))
		{
			Debug.LogWarning(text);
		}
	}

	public static void LogInvalidTween(Tween t)
	{
		LogWarning("This Tween has been killed and is now invalid");
	}

	public static void LogNestedTween(Tween t)
	{
		LogWarning("This Tween was added to a Sequence and can't be controlled directly", t);
	}

	public static void LogNullTween(Tween t)
	{
		LogWarning("Null Tween");
	}

	public static void LogNonPathTween(Tween t)
	{
		LogWarning("This Tween is not a path tween", t);
	}

	public static void LogMissingMaterialProperty(string propertyName)
	{
		LogWarning($"This material doesn't have a {propertyName} property");
	}

	public static void LogMissingMaterialProperty(int propertyId)
	{
		LogWarning($"This material doesn't have a {propertyId} property ID");
	}

	public static void LogRemoveActiveTweenError(string errorInfo, Tween t)
	{
		LogWarning($"Error in RemoveActiveTween ({errorInfo}). It's been taken care of so no problems, but Daniele (DOTween's author) is trying to pinpoint it (it's very rare and he can't reproduce it) so it would be awesome if you could reproduce this log in a sample project and send it to him. Or even just write him the complete log that was generated by this message. Fixing this would make DOTween slightly faster. Thanks.", t);
	}

	public static void LogAddActiveTweenError(string errorInfo, Tween t)
	{
		LogWarning($"Error in AddActiveTween ({errorInfo}). It's been taken care of so no problems, but Daniele (DOTween's author) is trying to pinpoint it (it's very rare and he can't reproduce it) so it would be awesome if you could reproduce this log in a sample project and send it to him. Or even just write him the complete log that was generated by this message. Fixing this would make DOTween slightly faster. Thanks.", t);
	}

	public static void SetLogPriority(LogBehaviour logBehaviour)
	{
		switch (logBehaviour)
		{
		case LogBehaviour.Default:
			_logPriority = 1;
			break;
		case LogBehaviour.Verbose:
			_logPriority = 2;
			break;
		default:
			_logPriority = 0;
			break;
		}
	}

	public static bool ShouldLogSafeModeCapturedError()
	{
		switch (DOTween.safeModeLogBehaviour)
		{
		case SafeModeLogBehaviour.None:
			return false;
		case SafeModeLogBehaviour.Normal:
		case SafeModeLogBehaviour.Warning:
			return _logPriority >= 1;
		default:
			return true;
		}
	}

	private static string GetDebugDataMessage(Tween t)
	{
		string message = "";
		AddDebugDataToMessage(ref message, t);
		return message;
	}

	private static void AddDebugDataToMessage(ref string message, Tween t)
	{
		if (t == null)
		{
			return;
		}
		bool flag = t.debugTargetId != null;
		bool flag2 = t.stringId != null;
		bool flag3 = t.intId != -999;
		if (flag || flag2 || flag3)
		{
			message += "DEBUG MODE INFO ► ";
			if (flag)
			{
				message += $"[tween target: {t.debugTargetId}]";
			}
			if (flag2)
			{
				message += $"[stringId: {t.stringId}]";
			}
			if (flag3)
			{
				message += $"[intId: {t.intId}]";
			}
			message += "\n";
		}
	}
}
